#! /bin/sh

### BEGIN INIT INFO
# Provides:          cloud9
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Cloud 9 IDE
# Description:       Manage Cloud 9 IDE
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "cloud9 - START... "
    
    sh /etc/c9start.sh </dev/null >/var/log/cloud9.log 2>&1 &


    ;;
  stop)
    echo "Stopping cloud9"
    
    echo "Unable to stop cloud9"
    
    ;;
  *)
    echo "Usage: service cloud9 {start|stop}"
    exit 1
    ;;
esac

exit 0
